baseURL = "https://blog.limewolf.top"
languageCode = "zh-cn"
title = "Limewolf的小窝"
theme = "neo-log"
defaultContentLanguage = "zh-cn"
enableEmoji = true
enableGitInfo = true

[pagination]
pagerSize = 5

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]

[services]
[services.googleAnalytics]
ID = "G-L0VX1GGSP1"
