[zh-cn]
contentDir = "content/zh-cn"
languageName = "简体中文"
languageCode = "zh-cn"
title = "莱姆狼"
weight = 1

[en]
contentDir = "content/en"
languageName = "English"
languageCode = "en"
title = "limewolf"
weight = 2