[[navbar]]
  identifier = "home"
  name = "Home"
  url = "/en"
  weight = 1

[[navbar]]
  identifier = "posts"
  name = "Posts"
  url = "/en/posts"
  weight = 2

[[navbar]]
  identifier = "projects"
  name = "Projects"
  url = "/en/projects"
  weight = 3

[[navbar]]
  identifier = "stories"
  name = "Story"
  url = "/en/stories"
  weight = 4

[[navbar]]
  identifier = "guestbook"
  name = "Guestbook"
  url = "/en/guestbook"
  weight = 5

[[navbar]]
  identifier = "about"
  name = "About"
  url = "/en/about"
  weight = 6